import { Product } from './types'

export function getMockProducts(query: string): Product[] {
  const q = query.toLowerCase()
  const base: Product[] = [
    {
      id: 'amz-1',
      title: `${query} - Premium Quality | Best Seller`,
      price: 29.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}1/400/400`,
      url: `https://www.amazon.com/s?k=${encodeURIComponent(query)}&tag=cavoserboss-21`,
      source: 'amazon',
      rating: 4.5,
      reviewCount: 1243,
      shipping: 'Free shipping with Prime',
    },
    {
      id: 'amz-2',
      title: `${query} Pro Edition - Top Rated`,
      price: 49.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}2/400/400`,
      url: `https://www.amazon.com/s?k=${encodeURIComponent(query)}+pro&tag=cavoserboss-21`,
      source: 'amazon',
      rating: 4.7,
      reviewCount: 892,
      shipping: 'Free shipping with Prime',
    },
    {
      id: 'ali-1',
      title: `${query} Wholesale - Factory Direct Price`,
      price: 8.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}3/400/400`,
      url: `https://www.aliexpress.com/wholesale?SearchText=${encodeURIComponent(query)}`,
      source: 'aliexpress',
      rating: 4.2,
      reviewCount: 3456,
      shipping: 'Free shipping',
    },
    {
      id: 'ali-2',
      title: `Cheap ${query} - Ships from China`,
      price: 4.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}4/400/400`,
      url: `https://www.aliexpress.com/wholesale?SearchText=${encodeURIComponent(query)}+cheap`,
      source: 'aliexpress',
      rating: 4.0,
      reviewCount: 8901,
      shipping: 'Free shipping (15-30 days)',
    },
    {
      id: 'ebay-1',
      title: `${query} - New in Box | Fast Shipping`,
      price: 24.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}5/400/400`,
      url: `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(query)}`,
      source: 'ebay',
      rating: 4.3,
      reviewCount: 567,
      shipping: 'Ships in 1-2 days',
    },
    {
      id: 'ebay-2',
      title: `Vintage ${query} - Collector Item`,
      price: 74.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}6/400/400`,
      url: `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(query)}+vintage`,
      source: 'ebay',
      rating: 4.6,
      reviewCount: 234,
      shipping: 'Ships worldwide',
    },
    {
      id: 'etsy-1',
      title: `Handmade ${query} - Unique & Artisanal`,
      price: 39.99,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}7/400/400`,
      url: `https://www.etsy.com/search?q=${encodeURIComponent(query)}`,
      source: 'etsy',
      rating: 4.9,
      reviewCount: 312,
      shipping: 'Free shipping on orders over $35',
    },
    {
      id: 'etsy-2',
      title: `Custom ${query} - Personalized Gift`,
      price: 55.00,
      currency: 'USD',
      image: `https://picsum.photos/seed/${q}8/400/400`,
      url: `https://www.etsy.com/search?q=${encodeURIComponent(query)}+custom`,
      source: 'etsy',
      rating: 5.0,
      reviewCount: 89,
      shipping: 'Estimated 5-7 days',
    },
  ]
  return base
}
